-- ============================================
-- KPI 1: Total Revenue generated from all sales
-- ============================================
SELECT 
    SUM(total_price) AS [Total Revenue] -- Sum of total_price gives overall revenue
FROM pizza_sales


-- ============================================
-- KPI 2: Average Order Value (AOV)
-- ============================================
SELECT 
    SUM(total_price) / COUNT(DISTINCT order_id) AS AVERAGE_ORDER -- Total revenue divided by number of unique orders
FROM pizza_sales


-- ============================================
-- KPI 3: Total Quantity of Pizzas Sold
-- ============================================
SELECT 
    SUM(quantity) AS TOTAL_PIZZA_SOLD -- Total units of pizzas sold
FROM pizza_sales


-- ============================================
-- KPI 4: Total Number of Orders
-- ============================================
SELECT 
    COUNT(DISTINCT order_id) AS TOTAL_ORDER -- Counts unique orders placed
FROM pizza_sales


-- ============================================
-- KPI 5: Average Pizzas Sold Per Order
-- ============================================
SELECT 
    CAST(SUM(quantity) * 1.0 / COUNT(DISTINCT order_id) AS DECIMAL(10,2)) AS AVERAGE_PIZZA_SOLD 
    -- Average number of pizzas per order, casted to decimal for precision
FROM pizza_sales


-- ============================================
-- Analysis 1: Total Orders by Day of Week
-- ============================================
SELECT 
    DATENAME(WEEKDAY, order_date) AS ORDER_DAY, -- Extracts day name (Monday, Tuesday, etc.)
    COUNT(DISTINCT order_id) AS TOTAL_ORDER -- Number of unique orders per day
FROM pizza_sales
GROUP BY DATENAME(WEEKDAY, order_date), DATEPART(WEEKDAY, order_date) 
-- DATEPART used to maintain correct weekday order (Mon-Sun)
ORDER BY DATEPART(WEEKDAY, order_date)


-- ============================================
-- Analysis 2: Total Orders by Month
-- ============================================
SELECT 
    DATENAME(MONTH, order_date) AS ORDER_MONTH, -- Extracts month name
    COUNT(DISTINCT order_id) AS TOTAL_ORDER -- Orders per month
FROM pizza_sales
GROUP BY DATENAME(MONTH, order_date), DATEPART(MONTH, order_date)
-- DATEPART ensures correct chronological order (Jan-Dec)
ORDER BY DATEPART(MONTH, order_date)


-- ============================================
-- Analysis 3: Sales & % Contribution by Pizza Category
-- ============================================
SELECT 
    pizza_category, -- Category like Classic, Veggie, etc.
    (SUM(total_price) / (SELECT SUM(total_price) FROM pizza_sales)) * 100 AS PCT 
    -- Percentage contribution of each category to total revenue
    ,SUM(total_price) AS TOTAL_SALES -- Total sales per category
FROM pizza_sales
GROUP BY pizza_category


-- ============================================
-- Analysis 4: Sales & % Contribution by Pizza Size
-- ============================================
SELECT 
    pizza_size, -- Size like S, M, L, XL
    CAST((SUM(total_price) / (SELECT SUM(total_price) FROM pizza_sales)) * 100 AS DECIMAL(10,2)) AS PCT 
    -- Percentage contribution by size with 2 decimal precision
    ,SUM(total_price) AS TOTAL_SALES -- Total sales per size
FROM pizza_sales
GROUP BY pizza_size
ORDER BY PCT DESC -- Highest contributing size first


-- ============================================
-- Top Performers Analysis
-- ============================================

-- Top 5 pizzas by total revenue
SELECT TOP 5
    pizza_name,
    SUM(total_price) AS TOTAL_REVENUE -- Revenue generated by each pizza
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE DESC


-- Top 5 pizzas by total quantity sold
SELECT TOP 5
    pizza_name,
    SUM(quantity) AS TOTAL_QUANTITY -- Total units sold per pizza
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_QUANTITY DESC


-- Top 5 pizzas by number of orders
SELECT TOP 5
    pizza_name,
    COUNT(DISTINCT order_id) AS TOTAL_ORDER -- Number of orders containing each pizza
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_ORDER DESC


-- ============================================
-- Bottom Performers Analysis
-- ============================================

-- Bottom 5 pizzas by total revenue
SELECT TOP 5
    pizza_name,
    SUM(total_price) AS TOTAL_REVENUE -- Lowest revenue generating pizzas
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE ASC


-- Bottom 5 pizzas by total quantity sold
SELECT TOP 5
    pizza_name,
    SUM(quantity) AS TOTAL_QUANTITY -- Least sold pizzas
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_QUANTITY ASC


-- Bottom 5 pizzas by number of orders
SELECT TOP 5
    pizza_name,
    COUNT(DISTINCT order_id) AS TOTAL_ORDER -- Least ordered pizzas
FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_ORDER ASC